# Generated by Django 5.0.3 on 2024-11-01 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        default="img/product/dummy.png",
                        null=True,
                        upload_to="img/product",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "course_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("professor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SCHOOL_SUPPLIES", "School Supplies"),
                            ("SPORTS", "Sports"),
                            ("ELECTRONICS", "Electronics"),
                            ("FUNITURE", "Furniture"),
                            ("CLOTHING", "Clothing"),
                            ("BOOKS", "Books"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sold", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="api_product_created_15ee1e_idx"
                    )
                ],
            },
        ),
    ]
